/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as CustomerRouteRouteImport } from './routes/customer/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerRouteRouteImport } from './routes/manager/route'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RegisterTrainerRouteImport } from './routes/register-trainer'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as TrainerRouteRouteImport } from './routes/trainer/route'
import { Route as UiNavigationRouteImport } from './routes/ui-navigation'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as TrainerIndexRouteImport } from './routes/trainer/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRouteRoute = CustomerRouteRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRouteRoute = ManagerRouteRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTrainerRoute = RegisterTrainerRouteImport.update({
  id: '/register-trainer',
  path: '/register-trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRouteRoute = TrainerRouteRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const UiNavigationRoute = UiNavigationRouteImport.update({
  id: '/ui-navigation',
  path: '/ui-navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/customer': typeof CustomerRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/trainer': typeof TrainerRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-trainer': typeof RegisterTrainerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ui-navigation': typeof UiNavigationRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/trainer/': typeof TrainerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-trainer': typeof RegisterTrainerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ui-navigation': typeof UiNavigationRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/staff': typeof StaffIndexRoute
  '/trainer': typeof TrainerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/customer': typeof CustomerRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/trainer': typeof TrainerRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-trainer': typeof RegisterTrainerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ui-navigation': typeof UiNavigationRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/trainer/': typeof TrainerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customer'
    | '/manager'
    | '/staff'
    | '/trainer'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/register-trainer'
    | '/reset-password'
    | '/ui-navigation'
    | '/admin/'
    | '/customer/'
    | '/manager/'
    | '/staff/'
    | '/trainer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/register-trainer'
    | '/reset-password'
    | '/ui-navigation'
    | '/admin'
    | '/customer'
    | '/manager'
    | '/staff'
    | '/trainer'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customer'
    | '/manager'
    | '/staff'
    | '/trainer'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/register-trainer'
    | '/reset-password'
    | '/ui-navigation'
    | '/admin/'
    | '/customer/'
    | '/manager/'
    | '/staff/'
    | '/trainer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CustomerRouteRoute: typeof CustomerRouteRouteWithChildren
  ManagerRouteRoute: typeof ManagerRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  TrainerRouteRoute: typeof TrainerRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RegisterTrainerRoute: typeof RegisterTrainerRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UiNavigationRoute: typeof UiNavigationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-trainer': {
      id: '/register-trainer'
      path: '/register-trainer'
      fullPath: '/register-trainer'
      preLoaderRoute: typeof RegisterTrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-navigation': {
      id: '/ui-navigation'
      path: '/ui-navigation'
      fullPath: '/ui-navigation'
      preLoaderRoute: typeof UiNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CustomerRouteRouteChildren {
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteRouteChildren: CustomerRouteRouteChildren = {
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteRouteWithChildren = CustomerRouteRoute._addFileChildren(
  CustomerRouteRouteChildren,
)

interface ManagerRouteRouteChildren {
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteRouteChildren: ManagerRouteRouteChildren = {
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteRouteWithChildren = ManagerRouteRoute._addFileChildren(
  ManagerRouteRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

interface TrainerRouteRouteChildren {
  TrainerIndexRoute: typeof TrainerIndexRoute
}

const TrainerRouteRouteChildren: TrainerRouteRouteChildren = {
  TrainerIndexRoute: TrainerIndexRoute,
}

const TrainerRouteRouteWithChildren = TrainerRouteRoute._addFileChildren(
  TrainerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CustomerRouteRoute: CustomerRouteRouteWithChildren,
  ManagerRouteRoute: ManagerRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  TrainerRouteRoute: TrainerRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RegisterTrainerRoute: RegisterTrainerRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UiNavigationRoute: UiNavigationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
